### ISSUE TITLE
Error when sending GET request for CS:GO API

### ISSUE THREAD

**Issue by GrashGarrett** [TrackerNetwork/TRN.Developers#11]
`<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
</head>
<script>

    $(document).ready(function(){
        $.ajax({
            method: "GET",
            url: "https://public-api.tracker.gg/v2/csgo/standard/profile/steam/76561198008049283",
            headers: {
                "TRN-Api-Key" : "APIKEY"
            },
            success: function(data){
                console.log(data);
            }
        })
    })
    

</script>`
I keep getting this error when using this jquery to take data from the api: 
(API is just a placeholder so I don't post my key online)
> Access to XMLHttpRequest at 'https://public-api.tracker.gg/v2/APItest.php:1csgo/standard/profile/steam/76561198008049283' from origin 'http://foothillertech.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://tracker.gg' that is not equal to the supplied origin.

**Comment by lwansbrough** [comment]
Our API currently doesn't support cross-origin requests. This means you'll have to proxy your requests through a web server. (This is also a good idea in order to keep your API key private.)
