### ISSUE TITLE
Can't reach the API Key from "My apps"

### ISSUE THREAD

**Issue by w-muskus** [TrackerNetwork/TRN.Developers#12]
Hi, 

I don't know why but this site does not work properly for me, when I open the app page
https://tracker.gg/developers/apps/3b48ead8-32c6-4ae3-a447-bae4e4161ff7

 console says:

"41.0276301a5.js:1 Uncaught (in promise) TypeError: Cannot read property 'email' of null"

And then after 20-30 seconds returns me back to https://tracker.gg/developers/apps/ 

Just can't even get the API Key for my app becouse of this, I can;t open app details only thing I can get is infinite animation of TRN logo like on screenshot

https://imagizer.imageshack.com/img923/7342/4tLUIA.png

Please help me finish my app, thanks for help :)

**Comment by lwansbrough** [comment]
Thanks for the bug report. We'll get this fixed ASAP.
