### ISSUE TITLE
Error while trying to hit the Fortnite Profile endpoint and the playername end in .

### ISSUE THREAD

**Issue by MyNameIsDark01** [TrackerNetwork/TRN.Developers#18]
I received the following response:

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>404 - File or directory not found.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
<div class="content-container"><fieldset>
<h2>404 - File or directory not found.</h2>
<h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
</fieldset></div>
</div>
</body>
</html>`

When I'm trying to hit "https://api.fortnitetracker.com/v1/profile/pc/imnotnameh."
It's very weird, if I search this playername on the website It give me a result.

![image](https://user-images.githubusercontent.com/48729254/71598240-632fbf00-2b46-11ea-9730-1bcc4ccace74.png)

**Comment by bladefist** [comment]
@MyNameIsDark01 fixed
