### ISSUE TITLE
Valorant TRN API

### ISSUE THREAD

**Issue by ShelyGanz** [TrackerNetwork/TRN.Developers#25]
Good day!
When will it be possible to use the TRN API for Valorant?

**Comment by SquatchHunter** [comment]
G'Day,

TheTrackerNetwork will not be opening a public facing API for Valorant -> Riot will be, currently there is no ETA on when this API will be released, if you would like to know as soon as it goes live consider joining the [Discord](https://discord.gg/vqJeaht) and watching out for either a post from one of the site owners or myself when the API launches

Thanks,
Squatch_
Community Support & Discord Mod for TheTrackerNetwork.
