### ISSUE TITLE
Division 2 - Wrong GearScore value

### ISSUE THREAD

**Issue by ghost** [TrackerNetwork/TRN.Developers#26]
Hello, 

The GearScore is not good. 
Actual value on website  : 921
In the game : 812

https://tracker.gg/division-2/profile/uplay/Psyonix_0/overview

**Comment by SquatchHunter** [comment]
G'day,

There are a few issues with the Division Website & API, we are aware of all the mismatched numbers and some are just 0 for no reason, this is down to Ubisoft's API they have provided us being incomplete and not updated for a while.
Please be patient like we are in hoping we will see an update to it, in the meantime you can join our [Discord](discord.gg/trackernetwork) for more up to date information and quicker response times.

Thanks,
Squatch_
Community Support & Discord Mod for TheTrackerNetwork.

**Comment by ghost** [comment]
Ok 
I can I find the  Ubisoft's API ? Is this public ?

Thx for the answer !

**Comment by SquatchHunter** [comment]
Sadly, no.
It's a private API given to select partners who have been given access.

**Comment by ghost** [comment]
Ok it's really bad for players :-( 

Thx a lot
have a good day =)
