### ISSUE TITLE
BF5 API support

### ISSUE THREAD

**Issue by giacolab** [TrackerNetwork/TRN.Developers#3]
Hi guys,

any news on the API support for BFV? I was an avid user of your API for BF1 and I would really love to see it for BFV as well, both for building my own stats and my clan's

Thank you for your work!
Jack

**Comment by bladefist** [comment]
@thejackhome Unfortunately we are not allowed to provide a BFV api.

**Comment by z1haze** [comment]
how did you get the ability to do so then?

**Comment by SquatchHunter** [comment]
G'day z1haze,

Can you clarify or open a new issue? We do not have permission to share the BFV API, we have been given a closed API to use for our service in regards to stats.

Thanks,
Squatch_
Community Support & Discord Admin for TheTrackerNetwork.

**Comment by z1haze** [comment]
How did you obtain this API? Did you purchase it? Monopolies are not good, especially when you are a third party
