### ISSUE TITLE
ERROR: An unhandled exception has occured in the system. Please try again. 

### ISSUE THREAD

**Issue by dabitsr** [TrackerNetwork/TRN.Developers#33]
I'm getting the next error when requesting to the CSGO API: 
`
code: null,
      message: 'An unhandled exception has occured in the system. Please try again.',
      data: {}
`

My code:

const axios = require("axios");
axios
  .get("https://public-api.tracker.gg/v2/csgo/standard/profile/steam/dabitsr", {
    headers: { "TRN-Api-Key": my-key },
  })
  .then((res) => console.log(res))
  .catch((err) => console.log(err.response.data));

**Comment by bladefist** [comment]
Should be fixed now.

**Comment by dabitsr** [comment]
Fixed! Thank you!
