### ISSUE TITLE
Cross-Origin Issue

### ISSUE THREAD

**Issue by margyrop** [TrackerNetwork/TRN.Developers#44]
When I attempt to make a fetch request I get a CORS error.

My request:

```fetch(`https://public-api.tracker.gg/v2/apex/standard/profile/${platform}/${user}`,
        {
            mode: 'cors',
            headers: new Headers({
                'Content-Type': 'application/json',
                'X-TRN-Api-Key': 'key-here',
                'accept': 'application/json'
            })
        })```

Using `no-cors` limits to simple requests to that is not an option.

How do I access the API?

- ReactJS app
- Fetch Request

**Comment by sgtfrankieboy** [comment]
We don't support calling the API from the web. You will have to use an intermediate server to make the API calls.
