### ISSUE TITLE
Bulk data? (Apex Legends)

### ISSUE THREAD

**Issue by nanodeath** [TrackerNetwork/TRN.Developers#49]
All of the APIs listed [here](https://tracker.gg/developers/docs/titles/apex) are for getting stats for individual profiles. Is there any way to get bulk data for _all_ profiles? Anonymized would be fine, or delayed (e.g. daily exports).

This would enable some pretty cool reporting, such as:
* Which legends are the most popular? How do these shift over time?
* Which legends are the top players choosing?

Somewhat related, bulk data could be grouped by matches, which would yield other ideas for analytics.

**Comment by lwansbrough** [comment]
Sorry, we don't offer bulk exports for a myriad of reasons, but we're always improving our internal tooling and may be able to provide this information on the site sometime in the future.
