### ISSUE TITLE
R6S API Support

### ISSUE THREAD

**Issue by MayhemBill** [TrackerNetwork/TRN.Developers#5]
I was looking for a decent API for R6S, and I currently use your csgo api and was hoping you could do one for R6S

**Comment by bladefist** [comment]
@MayhemBill It's on the roadmap for sure. I'll talk to @lwansbrough and get you an estimated ETA.

**Comment by MayhemBill** [comment]
That would be awesome, You guys have an amazing tracker system and api so far!

**Comment by lwansbrough** [comment]
@MayhemBill We don't have an exact timeline for you, but it's probably a couple weeks away at most.

**Comment by MayhemBill** [comment]
Well hey, whenever you guys get it, can you post here?

**Comment by bladefist** [comment]
Sure

**Comment by Alsharad** [comment]
Any updates regarding the R6 API?

**Comment by LexusSpeed03** [comment]
I am second that any updates?

**Comment by ahmedrafayat** [comment]
I am third, any updates?

**Comment by ryucz** [comment]
Still no update?

**Comment by vlizanae** [comment]
This would be a really nice addition

**Comment by SquatchHunter** [comment]
Hey Guys,
Quick update - this is still on the cards for now but we are having other problems currently which are pushing this back, most notably we are towards our upper limit on what we can actually host with what we have so far, I know its a pain as there are no "amazing" APIs for Siege, but this will just have to wait.
You can always consider joining our [Discord](discord.gg/trackernetwork) for more news on the matter as it happens

Thanks,
Squatch_
Community Support & Discord Mod for TheTrackerNetwork.

**Comment by AlirezaDaryani** [comment]
any update?

**Comment by ZeroLogic0** [comment]
Second to ask for update.

**Comment by stankarp** [comment]
Any update on this one?

**Comment by Bengeljo** [comment]
Any Updates ?

**Comment by maxoyed** [comment]
Any Updates ?

**Comment by xorth** [comment]
We won't be offering this for now.  Sorry.

**Comment by Shhlumpedayden** [comment]
Still no updates?

**Comment by maxoyed** [comment]
> Still no updates?

Seems not yet

**Comment by sqy941013** [comment]
any updates?

**Comment by Fejbien** [comment]
Any update?

**Comment by swagdotsh** [comment]
Still no updates?
