### ISSUE TITLE
Call of Duty Modern Warfare and Cold War stats API endpoint?

### ISSUE THREAD

**Issue by zdanman** [TrackerNetwork/TRN.Developers#56]
What are the endpoints for Tracker.gg Cold War and Modern Warfare and Warzone stats.

I've tried....

https://public-api.tracker.gg/api/v1/modern-warfare/standard/profile/battlenet/BigDuke6%2311123

and

https://public-api.tracker.gg/api/v2/modern-warfare/standard/profile/battlenet/BigDuke6%2311123
https://public-api.tracker.gg/v2/modern-warfare/standard/profile/battlenet/BigDuke6%2311123

I'm getting either no data back or

**The HTTP resource that matches the request URI 'http://api.tracker.gg/error' does not support the API version '2'**

Please help?!

Yes I am sending the API key like so...

`````
get_player($url)
{
   $headers = array(	'content-type: application/json',    'TRN-Api-Key: '.$this->APIKEY  );
		
   $ch = curl_init();
   $options = array(	CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_2_0,
			CURLOPT_URL => $url,
			CURLOPT_RETURNTRANSFER => 1,
			CURLOPT_SSL_VERIFYPEER => false,
			CURLOPT_HTTPHEADER => $headers );

   curl_setopt_array($ch, $options);
   $output = curl_exec($ch);
   curl_close($ch);
   return $output;
}

**Comment by bladefist** [comment]
We're not allowed to share these apis.    All of the apis we can share are documented here: https://tracker.gg/developers
