### ISSUE TITLE
Valorant API Support

### ISSUE THREAD

**Issue by lolzzzyo** [TrackerNetwork/TRN.Developers#58]
Would be nice if you could make one for Valorant :)

**Comment by SquatchHunter** [comment]
Hey lolzzyo,

I am sorry to inform you but that just isnt possible with Riots current restrictions that have been put in place - to host one would ultimately end up with our developer access being revoked and would lead to the site going down.
You can apply for access to the API over at [Riot's Offical Developer Site](https://developer.riotgames.com/). However they are pretty strict with access at the time of writting.

Thanks,
Squatch_
Community Support & Discord Admin for TheTrackerNetwork

**Comment by KaylenTPillay** [comment]
A little late to this. It's quite sad that the API is super strict. Could we close this issue?
