### ISSUE TITLE
Splitgate api python not working...

### ISSUE THREAD

**Issue by jostmoritz** [TrackerNetwork/TRN.Developers#59]
Thats my code:

-----------------------------------------------------------------------------------------------------

from requests.auth import HTTPBasicAuth
import requests
import json
import discord

user = "76561199007449539"

url = "https://public-api.tracker.gg/v2/splitgate/standard/profile/steam/" +user
headers = {'Accept': 'application/json'}
auth = HTTPBasicAuth('TRN-Api-Key', 'MY_API_KEY')

response = requests.get(url, headers=headers, auth=auth)
print(response.text)

-----------------------------------------------------------------------------------------------------
output = "{"message":"No API key found in request"}"

Anyboy know why this isnt working?

**Comment by SquatchHunter** [comment]
Hey Mo18769,
You have misread the docs and included your API key in the wrong part of the call
try doing the following;
```python
url = "https://public-api.tracker.gg/v2/splitgate/standard/profile/steam/" +user
headers = {
    'Accept': 'application/json',
    'TRN-Api-Key' : '{YOUR_KEY_HERE}'
}
```
For further assistance and for a faster response time feel free to join our discord and use the #trn-api channel, we have plenty of friendly community members who will try their best to assist you :)
https://discord.com/invite/trackernetwork

Thanks,
Squatch_
Community Support & Discord Admin for TheTrackerNetwork

edit: missed a coma

**Comment by jostmoritz** [comment]
Thanks
