### ISSUE TITLE
Help with Warzone API

### ISSUE THREAD

**Issue by LPLPenguin** [TrackerNetwork/TRN.Developers#69]
Hi All,

I'm new here so sorry if this isn't the place! I have the below code do display some Warzone KD info which comes from cod.tracker.gg and it's recently stopped working. I've tried to debug it myself but I can't quite figure out the issue. Any help would be greatly appreciated! 

$(eval s=$(urlfetch json https://api.tracker.gg/api/v2/warzone/standard/profile/atvi/Reaz%7644166/).data.segments[1].stats; r=s.kdRatio.value; k=s.kills.value; d=s.deaths.value; w=s.wins.value; dw=s.downs.value; whp=s.weeklyHeadshotPct.value; wk=s.weeklyKdRatio.displayValue; $(channel) has: Wins: ${w} | Kills: ${k} | Downs: ${dw} | Deaths: ${d} | KD: ${r} | Weekly KD: ${wk} | Weekly Headshot: ${whp}%)

The only thing that changed lately was the username, but all the same publicity settings apply. Thanks again

**Comment by bladefist** [comment]
We don't offer a warzone api.
