### ISSUE TITLE
BFV API 403

### ISSUE THREAD

**Issue by degoya** [TrackerNetwork/TRN.Developers#70]
Since some days i get a 403 error when  i try to access **https://api.tracker.gg/api/v2/bfv/standard/profile/origin/** . worked before without anyproblems. it still works from my friends server but not from mine. have i been blocked?

**Comment by KyleMo** [comment]
As far as I know, they have shut down the BFV API.

**Comment by bladefist** [comment]
We don't offer a BFV api. We've stated this a few times. Furthermore,  when we offer an api, we document it.
