### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by Nyalian** [TrackerNetwork/TRN.Developers#72]
![Screenshot_20220317_010313](https://user-images.githubusercontent.com/20660730/158646755-2ec1703b-5110-40b6-a440-08cc3ea25535.jpg)
i use Python and i am still blocked.
is there something wrong with my ip?

**Comment by bladefist** [comment]
Can you provide the ray ID and ip from the image here?

**Comment by Nyalian** [comment]
6ecf108f9f9b9806
240e:476:ff92:28e3:88ec:f7ff:fe33:dcc3

**Comment by Nyalian** [comment]
oh 
the ray id is changed
but the ip is not changed

**Comment by kelecc** [comment]
> oh the ray id is changed but the ip is not changed
I have the same problem. Can you help me

**Comment by Nyalian** [comment]
are the chinese（both mainland and hk）ips blocked？

**Comment by kelecc** [comment]
> are the chinese（both mainland and hk）ips blocked？

The bfv API I can access with the browser, with postman will be 403, the open APIs in the document are all 403. Thank you

**Comment by bladefist** [comment]
Please use a datacenter outside of China, we have blocked China due to excessive abuse.

@kelecc we do not offer a BFV api.
