### ISSUE TITLE
Can't use Apex API

### ISSUE THREAD

**Issue by akiamatsukaze** [TrackerNetwork/TRN.Developers#73]
I applied for Apex API and I got one, then I put it to use. But my python raised an error of "API key invalid or missing". I don't know why is this happening, maybe I should apply for production use?

**Comment by ghost** [comment]
Could you provide your code? Maybe I can offer some help.

**Comment by akiamatsukaze** [comment]
> 
I already found my problem.It seems datacenter in China can't use API provided by TRN,so my API key was denied.

**Comment by bladefist** [comment]
Correct, we do not allow access to the api from a China datacenter because of abuse and China datacenters do not respond to our abuse reports.  Please use a data center outside of China.
