### ISSUE TITLE
No permission for valorant api

### ISSUE THREAD

**Issue by ImNico00** [TrackerNetwork/TRN.Developers#77]
Hi, my profile on the tracker site was approved for production use.
I just want to take some players information with the valorant api using my api key but it doesn't works.

`            await fetch("https://public-api.tracker.gg/v2/valorant/standard/profile/riot/" + username, {
                headers: {
                'method': 'GET',
                'Accept-Encoding': 'gzip',
                "Content-Type": "application/json;charset=utf-8",
                "TRN-Api-Key": ${settings['TRN-Api-Key']}
                }
            })`

I'm using fetch in my discord bot. Can someone help me please?

**Comment by bladefist** [comment]
We don't offer a valorant api, it's against Riot's TOS.

**Comment by abdullah-2005-3** [comment]
@ImNico00 DID YOU FIX IT ?
