### ISSUE TITLE
OverWatch API-BattleNet not working

### ISSUE THREAD

**Issue by Austinmoore1492** [TrackerNetwork/TRN.Developers#8]
Everything else is working fine (Xbox and PlayStation) but I cannot load any profiles that have battlenet accounts.

**Comment by lwansbrough** [comment]
Hey, thanks for reporting. Can you provide the account that doesn't work? A number of accounts that I tested appear to work fine.

**Comment by Austinmoore1492** [comment]
DoctorWhat#11993, then i tried a few of https://overwatchtracker.com/

**Comment by Austinmoore1492** [comment]
I'm pretty sure it has something to do with the # in the BattleNet ID. Just having looked at the console when I fetch a BattleNet Profile it excludes the #. So if i look for DoctorWhat#11993 it is only fetching the DoctorWhat potion. I figured since it was working on other platforms it was something I had done.

**Comment by lwansbrough** [comment]
You have to URL encode the name before you append it to the API URL. # should become %23

**Comment by amosda4183** [comment]
I am having this issue as well. In my own application as well the documentations 'try it out' drawer. PSN and Xbox Live are working fine, but there is no response to a request for the Battlenet platform, after attempting multiple user accounts. I also attempted the request using the URL encoding you mentioned in a previous comment and could not get anything back.

**Comment by Austinmoore1492** [comment]
Do you happen to have a link to the code and did you use encodeURI or encodeURIComponent?

**Comment by amosda4183** [comment]
When I click the 'Make Request' Button here, nothing happens, though you can see in the GET request that the URL is properly encoded before being sent. When the button is clicked with the default input, or any other input, nothing happens.

![tracker-network](https://user-images.githubusercontent.com/13411717/63630322-891ce400-c5e7-11e9-8df8-32e517b33745.PNG)
![tracker-network-2](https://user-images.githubusercontent.com/13411717/63630323-891ce400-c5e7-11e9-8170-a7939418cb27.PNG)

**Comment by amosda4183** [comment]
Below is the code from my local environment. Using encodeURIComponent I can see that the platformId is properly encoded and attached to the request that is sent, but it returns an empty object. So I'm not sure what the issue could be. The PSN and Xbox Live requests are working fine, there only seems to be an issue with Battlenet.
![tracker-network-3](https://user-images.githubusercontent.com/13411717/63630349-c5e8db00-c5e7-11e9-9581-add048c7875b.PNG)
![tracker-network-4](https://user-images.githubusercontent.com/13411717/63630350-c5e8db00-c5e7-11e9-92ca-c4dd1934053c.PNG)

**Comment by Austinmoore1492** [comment]
I still hve the same issue. On mine I can search for profiles from the overwatch tracker network but I cannot find my own profile. Not sure what the issue is there.

**Comment by lwansbrough** [comment]
@amosda4183 You exposed your API key publicly, you should create a new application. This key is private. The user `Kabaji#21523` has a private profile. You should be receiving a 451 response from our server (indicating the profile is private -- we also provide an error message as JSON in the response.) Check the network requests tab.

**Comment by lwansbrough** [comment]
@Austinmoore1492 Use `encodeURIComponent`

**Comment by Austinmoore1492** [comment]
I have used it, I can pull data for some battlenet ids just not mine.

**Comment by Austinmoore1492** [comment]
Which I assume is because the profile is private, as you stated.
