### ISSUE TITLE
Battlefield 2042 support

### ISSUE THREAD

**Issue by sgammon** [TrackerNetwork/TRN.Developers#80]
Hey there TRN,

I am interested in developing custom stream bots / overlays for Battlefield 2042. I'm looking for a stats API I can use under the hood. I'm already a paid customer of TRN, but I'd love to use the developer APIs to build this, if possible. Is BF2042 support on the way? Is there a way the community can contribute to bring support faster? Thank you in advance and looking forward to developing with you guys.

**Comment by xorth** [comment]
We are not allowed to offer APIs for BF franchise.  Sorry.
