### ISSUE TITLE
Server Error in '/' Application when trying to create an API key

### ISSUE THREAD

**Issue by nastyam1994** [TrackerNetwork/TRN.Developers#82]
Hi, I have been trying to generate the API key on https://fortnitetracker.com/site-api/create Every time I press "Generate API key" button, I get the following: 
Server Error in '/' Application. This type of page is not served. Description: The type of page you have requested is not served because it has been explicitly forbidden. Please review the URL below and make sure that it is spelled correctly. Requested URL: /site-api/create 

Please help. 

Thank you in advance! 
Nastya

**Comment by xorth** [comment]
We're no longer offering the Fortnite api to all.
