### ISSUE TITLE
Web Scraping Permission

### ISSUE THREAD

**Issue by Finalben7** [TrackerNetwork/TRN.Developers#85]
I'm building a website that needs to verify users Rocket League ranks upon account creation. I've gathered you can't access their API directly, but I stumbled across this https://github.com/kilroy-2/rl-rank-stats-web-scrap and was wondering if this is valid. It claims all I need is permission from TRN for it to work, please let me know if this is possible.

Thanks

**Comment by ViezeVingertjes** [comment]
Your answer is here: [https://tracker.gg/robots.txt](https://tracker.gg/robots.txt)

**Comment by xorth** [comment]
We are not allowed to offer apis for Rocket League, so no, it's not allowed.  Appreciate you asking!
