### ISSUE TITLE
Valorant API endpoint

### ISSUE THREAD

**Issue by andreluisfc** [TrackerNetwork/TRN.Developers#89]
Permission to access the Valorant Stats by API endpoint.
I'm trying to do an app to access the player stats on Valorant using the API endpoint but its not public, can we do it using another way or do you have plans to open this endpoint?
![image](https://user-images.githubusercontent.com/80536789/225037999-408f53ad-6f4f-4bd1-9b20-d47e536baf51.png)

**Comment by bladefist** [comment]
Riot does not allow us to offer any APIs for their games.  You'll need to use the official riot api.
