### ISSUE TITLE
Division 2 API no longer working

### ISSUE THREAD

**Issue by Jsayer7** [TrackerNetwork/TRN.Developers#94]
I have had an existing Discord bot that has worked for years suddenly stop working semi-recently.

The requests return a response of:
```{'message': 'Invalid authentication credentials'}```

I created a new app with a fresh API key and got the same result.

Simple python editor code attached.
<img width="620" alt="Screenshot 2023-11-14 at 3 53 20 PM" src="https://github.com/TrackerNetwork/TRN.Developers/assets/5124364/abb403d0-047a-431d-8883-b6174eb6cb02">

**Comment by Zubastic** [comment]
Same issue with apex.

**Comment by SquatchHunter** [comment]
Hey there

For some time now it is required that you go to our [Discord Server](https://discord.com/invite/trackernetwork) and read the pinned message in the #trn-api channel, due to some abuse all API keys are subject to manual approval.

**Comment by Jsayer7** [comment]
Confirmed after getting a new key it worked.
